# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

useDotenv: true

# The `service` block is the name of the service
service: mnist-inference
frameworkVersion: "3"
org: withcontext
app: mnist

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.9
  timeout: 29
  memorySize: 2048
  environment:
    SAGEMAKER_DEPLOYED_ENDPOINT: ${env:DEPLOY_SHA}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "sagemaker:*"
          Resource: "*"

custom:
  pythonRequirements:
    zip: true

# The `functions` block defines what code to deploy
functions:
  api:
    handler: api.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-python-requirements
