name: Count Commits in PR

on:
  pull_request:
    branches:
      - test

jobs:
  count-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Establish Github App Bot
        id: github-app-token
        uses: mercari/github-app-token-generator@v1
        with:
          app-id: ${{secrets.GH_APP_ID}}
          app-private-key: ${{secrets.GH_APP_PEM}}
          app-installation-id: ${{secrets.GH_APP_INSTALLATION_ID}}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "PR commits"
        run: |
          echo "PR_COMMITS=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_STEP_SUMMARY
