name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy_endpoint_to_lambda:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: Deploy Endpoint and Lambda to Public API Gateway
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        # Change this so that only ./src/serverless is checked out
        with:
          sparse-checkout: "src/serverless/"
          sparse-checkout-cone-mode: false
      #----------------------------------------------
      #       Setup Platform
      #----------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: us-east-1
      #----------------------------------------------
      #       Deploy Serverless
      #----------------------------------------------
      - name: Deploy SLS Endpoint
        id: deploy-sls
        env:
          DEPLOY_SHA: "05c0763"
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          rm .env
          npm install -g serverless
          npm ci
          serverless deploy --verbose
          URL="$(serverless info --verbose | grep endpoint | sed -n 's/^endpoint: ANY - //p')"
          echo "Endpoint Deployed :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "| Endpoint | URL |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-----|" >> $GITHUB_STEP_SUMMARY
          echo "| API Gateway | [Here]($URL/docs) |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        working-directory: ./src/serverless
  write-deployment-sha:
    name: Write Output
    runs-on: ubuntu-latest
    needs: deploy_endpoint_to_lambda
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Write Deployment SHA to .env file
        env: 
          DEPLOY_VALUE: "05c0763"
        run: |
          touch -c .env
          echo "DEPLOY_SHA=${DEPLOY_VALUE:0:7}" >> .env
        working-directory: ./src/serverless

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Serverless Deployment SHA"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  destroy_endpoint:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    name: Destroy Sagemaker Endpoint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use Github OIDC provider to assume the role
          role-to-assume: $${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: us-east-1

      - name: Destroy Sagemaker Endpoint
        id: destroy_endpoint
        env:
          EVENT_SHA: "05c076329917ea8566c828708db693fd5a125932"
        run: |
          aws sagemaker delete-endpoint --endpoint-name ${EVENT_SHA:0:7}
          echo "Endpoint Destroyed: ${EVENT_SHA:0:7}" >> "$GITHUB_STEP_SUMMARY"
