name: Deploy SLS
on:
  workflow_dispatch:

jobs:
  deploy_endpoint:
    name: Deploy Endpoint and Lambda to Public API Gateway
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        # Change this so that only ./src/serverless is checked out
        with:
          sparse-checkout: "src/serverless/"
          sparse-checkout-cone-mode: false
      #----------------------------------------------
      #       Setup Platform
      #----------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - run: ls -alht
        working-directory: ./src/serverless

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g serverless
        working-directory: ./src/serverless

      - run: npm ci
        working-directory: ./src/serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: us-east-1
      #----------------------------------------------
      #       Deploy Serverless
      #----------------------------------------------
      - name: Deploy SLS Endpoint
        env:
          DEPLOY_SHA: "05c0763"
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          serverless deploy --stage dev --region us-east-1
        working-directory: ./src/serverless 

      - name: Report Success
        run: |
          echo "Endpoint has been deployed successfully." >> "$GITHUB_OUTPUT"
