name: Deploy SLS
on:
  workflow_dispatch:

jobs:
  deploy_endpoint:
    name: Deploy Endpoint and Lambda to Public API Gateway
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      #----------------------------------------------
      #       Setup Node and Serverless
      #----------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            ./src/serverless/package.json
            ./src/serverless/package-lock.json

      - run: npm ci
        working-directory: ./src/serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: us-east-1
      #----------------------------------------------
      #       Deploy Serverless
      #----------------------------------------------
      - name: Deploy SLS Endpoint
        uses: serverless/github-action@v3.2.0
        env:
          DEPLOY_SHA: "05c0763"
        with:
          args: -c "cd ./src/serverless/ && sls deploy --region us-east-1 --config serverless.yml --stage prod --org withcontext --verbose"

      - name: Report Success
        run: |
          echo "Endpoint has been deployed successfully." >> "$GITHUB_OUTPUT"
