name: Destroy Endpoint
on:
  workflow_dispatch:

jobs:
  destroy_endpoint:
    # this job will only run if the PR has been closed without being merged
    name: Destroy Sagemaker Endpoint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use Github OIDC provider to assume the role
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: us-east-1

      - name: Destroy Sagemaker Endpoint
        id: destroy_endpoint
        env:
          EVENT_SHA: "05c076329917ea8566c828708db693fd5a125932"
        run: |
          aws sagemaker delete-endpoint --endpoint-name ${EVENT_SHA:0:7}
          echo "Endpoint Destroyed: ${EVENT_SHA:0:7}" >> "$GITHUB_STEP_SUMMARY"

      
    
    
      