name: Report Github Commit SHA
on:
  pull_request:
    branches:
      - master
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Report Github Commit SHA
        env:
          BASE_BRANCH: ${{github.sha}}
          EVENT_SHA: ${{github.event.pull_request.head.sha}}
          MERGE_SHA: ${{github.event.pull_request.base.sha}}
        run: |
          BASE_BRANCH_SHORT=$(echo $BASE_BRANCH | cut -c 1-7)
          EVENT_SHA_SHORT=$(echo $EVENT_SHA | cut -c 1-7)
          MERGE_SHA_SHORT=$(echo $MERGE_SHA | cut -c 1-7)
          echo "BASE_BRANCH: $BASE_BRANCH_SHORT" >> $GITHUB_STEP_SUMMARY
          echo "EVENT_SHA: $EVENT_SHA_SHORT" >> $GITHUB_STEP_SUMMARY
          echo "MERGE_SHA: $MERGE_SHA_SHORT" >> $GITHUB_STEP_SUMMARY
