name: Report Github Commit SHA
on:
  pull_request:
    branches:
      - master
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Report Github Commit SHA
        env:
          BASE_BRANCH: ${{github.sha}}
          EVENT_SHA: ${{github.event.pull_request.head.sha}}
          MERGE_SHA: ${{github.event.pull_request.base.sha}}
        run: |
          echo "BASE_BRANCH: $BASE_BRANCH" >> $GITHUB_STEP_SUMMARY
          echo "EVENT_SHA: $EVENT_SHA" >> $GITHUB_STEP_SUMMARY
          echo "MERGE_SHA: $MERGE_SHA" >> $GITHUB_STEP_SUMMARY
