name: SLS Debug

# only trigger on pull request closed events
on:
  workflow_dispatch:

jobs:
  deploy_endpoint_to_lambda:
    # this job will only run if the PR has been merged
    name: Deploy Endpoint and Lambda to Public API Gateway
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        # Change this so that only ./src/serverless is checked out
        with:
          sparse-checkout: "src/serverless/"
          sparse-checkout-cone-mode: false
      #----------------------------------------------
      #       Setup Platform
      #----------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: us-east-1
      #----------------------------------------------
      #       Deploy Serverless
      #----------------------------------------------
      - name: Deploy SLS Endpoint
        id: deploy-sls
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          source .env
          npm install -g serverless
          npm ci
          serverless deploy --verbose
          URL="$(serverless info --verbose | grep endpoint | sed -n 's/^endpoint: ANY - //p')"
          echo "Endpoint Deployed :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "| Endpoint | URL |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-----|" >> $GITHUB_STEP_SUMMARY
          echo "| API Gateway | [Here]($URL/docs) |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        working-directory: ./src/serverless
