name: Train Sagemaker Model
on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
        with:
            installer-parallel: true
            virtualenvs-create: true
            virtualenvs-in-project: true

      - name: Install Poetry Project
        run: |
          poetry install --no-interaction --no-root

      - name: Cache Poetry Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
  
      - name: Run Estimator.fit() Function.
        run: |
          source $VENV
          python3 src/mnist_sagemaker_ci_cd/lib/settings.py