name: Write Repo Deployment SHA
on:
  workflow_dispatch:

jobs:
  write-deployment-sha:
    name: Write Output
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Write Deployment SHA to .env file
        env: 
          DEPLOY_VALUE: "05c0763"
        run: |
          touch -c .env
          echo "DEPLOY_SHA=$DEPLOY_VALUE" >> .env
        working-directory: ./src/serverless

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Serverless Deployment SHA"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      
    
    
      